// * DEFINE ALL THE ACTION TYPES //
export const UserActions = {
    LOAD_USER: 'LOAD_USER',
    SET_USER_INFORMATION: 'SET_USER_INFORMATION',
    UPDATE_USER_INFROMATION: 'UPDATE_USER_INFROMATION',
    REMOVE_USER_INFORMATION: 'REMOVE_USER_INFORMATION'
}

export const StockActions = {
    SET_STOCK_DETAILS: "SET_STOCK_DETAILS",
    ADD_STOCK: "ADD_STOCK",
    UPDATE_STOCK: "UPDATE_STOCK",
    STOCK_BULK_REMOVE: "STOCK_BULK_REMOVE"
}